project:
  type: website
  output-dir: docs

website:
  title: "Ann Nibana S L"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Projects
      - href: about.qmd
        text: About
      - href: Ann_resume.pdf
        text: CV
      - text: Documentations
        menu:
          - href: files/assignments/landslide_code.html
            text: landslide_code 
          - href: files/assignments/landslidmap.html
            text: Landslide Map
          - href: files/assignments/LanduseNorciappt.pdf
            text: Landuse_Norcia  (PDF) 
          - href: files/assignments/HECPPT.pdf
            text: HECPPT (PDF) 
          - href: files/assignments/YOLOPPT.pdf
            text: YOLOPPT  (PDF)
          - href: files/assignments/yoloprojectreport.pdf
            text: YOLO Report  (PDF)
          - href: files/assignments/yolosummary.html
            text: Yolo Project summary
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual


  
