project:
  type: website
  output-dir: docs

website:
  title: "Ann Nibana S L"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: project.qmd
        text: Project
      - href: CV_Ann.pdf
        text: CV
      - text: Assignments
        menu:
          - href: files/assignments/Ann_Assignment1.pdf
            text: Assignment 1 (PDF)
          - href: files/assignments/Ann_Assignment2.pdf
            text: Assignment 2 (PDF) # Opens a Page with PDFs
          - href: files/assignments/AI_PPT.pdf
            text: PPT  (PDF) 
          - href: files/assignments/Ann_Assignment3.pdf
            text: Assignment 3  (PDF) 
          - href: files/assignments/Ann_Assignment4.pdf
            text: Assignment 4  (PDF) 
          - href: files/assignments/Ann_Assignment5.pdf
            text: Assignment 5  (PDF) 

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

