---
title: "About Me"
format: html
---

As a **GIS scholar**, currently I am pursuing my **Master of Science in GIS** at the **University of Texas at Dallas**, where I am deepening my expertise in **geospatial modeling, data visualization, and AI-driven GIS solutions**.

Prior to this, I completed a **Post Graduate Diploma in GIS** from **IUCGIST, India**, where I gained expertise in **spatial modeling, remote sensing, and GIS programming**. My academic foundation includes a **Master's and Bachelor's degree in Physics** from the **University of Kerala**, which helped me develop strong analytical and scientific skills, now applied in my geospatial research.

------------------------------------------------------------------------

### **My Interests & Expertise**

I am particularly interested in how **GIS, Python and Machine learning** can be used to: - **Analyze environmental changes** (land use, climate impact and disaster risk assessment). - **Develop interactive spatial visualizations** for real-world geospatial problems. **Apply machine learning to GIS** for predictive analytics and classification.

My academic and professional journey has allowed me to work on several impactful projects, integrating **Python, remote sensing techniques and statistical modeling** to generate actionable insights from geospatial data.
